### PR TITLE
Fix 'docker run' example arg order

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by brianhlin** [comment]
Oops, I think we also have to pass the environment

**Comment by matyasselmeci** [comment]
That actually matters? Ugh.

**Comment by brianhlin** [comment]
Yeah, opts go before container and command args D:

**Comment by brianhlin** [comment]
Alright, got it working: https://github.com/opensciencegrid/xcache/pull/60

And the README example has been fixed to reflect it

**Pull request merged**
